language: scala
scala:
   - 2.10.4
   - 2.11.2

script:
  - sbt -jvm-opts travis/jvmopts.compile ... compile
  - sbt -jvm-opts travis/jvmopts.test ... test

sbt_args: -no-colors -J-Xss2m

script: sbt -no-colors -J-Xss2m ++$TRAVIS_SCALA_VERSION test